services:

  app:
    build: .
    container_name: sprintflow-app

    ports:
      - "8082:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sprintflow_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    networks:
      - task-management-system_default

networks:
  task-management-system_default:
    external: true